title: Suhas S
logo: /assets/img/suhas_photo.jpg
description: Electronics and Instrumentation Engineering Graduate, currently working as a SAP SD Consultant for Infosys.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
